-- 吃瓜网数据库脚本

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50),
    avatar VARCHAR(500) DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN users.id IS 'ID';
COMMENT ON COLUMN users.username IS '用户名';
COMMENT ON COLUMN users.password IS '密码';
COMMENT ON COLUMN users.nickname IS '昵称';
COMMENT ON COLUMN users.avatar IS '头像URL';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.update_at IS '更新时间';
COMMENT ON TABLE users IS '用户表';

INSERT INTO users (username, password, nickname) VALUES ('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'sylvie233');

-- ====== RBAC 权限模型 ======
DROP TABLE IF EXISTS role_permission;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS permission;

-- 角色表
CREATE TABLE role (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(50) NOT NULL,
    description TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN role.id IS '角色ID';
COMMENT ON COLUMN role.code IS '角色标识';
COMMENT ON COLUMN role.name IS '角色名称';
COMMENT ON COLUMN role.description IS '角色描述';
COMMENT ON TABLE role IS '角色表';

-- 权限表（动态路由/菜单/按钮）
CREATE TABLE permission (
    id INT8 GENERATED BY DEFAULT AS IDENTITY,
    parent_id INT8 DEFAULT 0,
    title VARCHAR(50) NOT NULL,
    path VARCHAR(200) DEFAULT '',
    component VARCHAR(200) DEFAULT '',
    icon VARCHAR(50) DEFAULT '',
    permission_code VARCHAR(100) DEFAULT '',
    sort_order INT4 DEFAULT 0,
    visible BOOLEAN DEFAULT TRUE,
    permission_type VARCHAR(1) DEFAULT 'M',  -- M=菜单 B=按钮
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN permission.id IS '权限ID';
COMMENT ON COLUMN permission.parent_id IS '父级ID，0为顶级';
COMMENT ON COLUMN permission.title IS '名称';
COMMENT ON COLUMN permission.path IS '路由路径';
COMMENT ON COLUMN permission.component IS '组件路径';
COMMENT ON COLUMN permission.icon IS '图标';
COMMENT ON COLUMN permission.permission_code IS '权限标识';
COMMENT ON COLUMN permission.sort_order IS '排序';
COMMENT ON COLUMN permission.visible IS '是否可见';
COMMENT ON COLUMN permission.permission_type IS '类型：M=菜单 B=按钮';
COMMENT ON TABLE permission IS '权限菜单表';

-- 角色-权限关联表
CREATE TABLE role_permission (
    role_id INT8 NOT NULL REFERENCES role(id),
    menu_id INT8 NOT NULL REFERENCES permission(id),
    PRIMARY KEY (role_id, menu_id)
);
COMMENT ON COLUMN role_permission.role_id IS '角色ID';
COMMENT ON COLUMN role_permission.menu_id IS '权限ID';
COMMENT ON TABLE role_permission IS '角色权限关联表';

-- 用户-角色关联表
CREATE TABLE user_role (
    user_id INT8 NOT NULL REFERENCES users(id),
    role_id INT8 NOT NULL REFERENCES role(id),
    PRIMARY KEY (user_id, role_id)
);
COMMENT ON COLUMN user_role.user_id IS '用户ID';
COMMENT ON COLUMN user_role.role_id IS '角色ID';
COMMENT ON TABLE user_role IS '用户角色关联表';

-- ====== 种子数据 ======

-- 插入角色
INSERT INTO role (code, name, description) VALUES
    ('admin', '管理员', '系统管理员，拥有所有权限'),
    ('reviewer', '审核员', '文章审核员，可审核文章并查看基础数据'),
    ('user', '普通用户', '普通用户，可创作和提交文章');

-- 给现有 admin 用户分配 admin 角色
INSERT INTO user_role (user_id, role_id)
SELECT (SELECT id FROM users WHERE username = 'admin'), (SELECT id FROM role WHERE code = 'admin');

-- 权限菜单种子数据
-- 顶级菜单: parent_id=0
INSERT INTO permission (id, parent_id, title, path, icon, permission_code, sort_order, permission_type) VALUES
(1,  0, '首页',     '/',                 'HomeOutlined',      'dashboard:view',   1, 'M');

-- 首页按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(11, 1, '刷新数据',       'dashboard:refresh',        1, 'B'),
(12, 1, '文章统计',       'dashboard:article:stats',  2, 'B'),
(13, 1, '发布活跃度',     'dashboard:article:chart',  3, 'B'),
(14, 1, '最近发布文章',   'dashboard:article:recent', 4, 'B'),
(15, 1, '分类统计卡片',   'dashboard:category:stats', 5, 'B'),
(16, 1, '标签统计卡片',   'dashboard:tag:stats',      6, 'B'),
(17, 1, '评论统计卡片',   'dashboard:comment:stats',  7, 'B'),
(18, 1, '用户统计卡片',   'dashboard:user:stats',     8, 'B');
-- 顶级菜单(续)
INSERT INTO permission (id, parent_id, title, path, icon, permission_code, sort_order, permission_type) VALUES
(2,  0, '文章管理', '',                   'FileOutlined',      'article:menu',     2, 'M'),
(3,  0, '分类管理', '/categories',        'AppstoreOutlined',  'category:list',    3, 'M'),
(4,  0, '标签管理', '/tags',              'TagsOutlined',      'tag:list',         4, 'M'),
(5,  0, '评论管理', '/comments',          'MessageOutlined',   'comment:list',     5, 'M'),
(6,  0, '系统管理', '',                   'SettingOutlined',   'system:menu',      6, 'M');

-- 文章管理子菜单: parent_id=2
INSERT INTO permission (id, parent_id, title, path, icon, permission_code, sort_order, permission_type) VALUES
(21, 2, '文章列表', '/articles',          'FileTextOutlined',  'article:list',     1, 'M'),
(22, 2, '审核管理', '/articles/pending',  'AuditOutlined',     'article:review',   2, 'M'),
(23, 2, '审核记录', '/articles/records',  'HistoryOutlined',   'article:records',  3, 'M');

-- 系统管理子菜单: parent_id=6
INSERT INTO permission (id, parent_id, title, path, icon, permission_code, sort_order, permission_type) VALUES
(61, 6, '用户管理', '/system/users',      'UserOutlined',              'user:list',   1, 'M'),
(62, 6, '角色管理', '/system/roles',      'SafetyCertificateOutlined', 'role:list',   2, 'M'),
(63, 6, '菜单管理', '/system/menus',      'MenuOutlined',             'role:menu',    3, 'M');

-- 按钮权限: parent_id 指向所属菜单, permission_type='B'
-- 文章列表按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(211, 21, '新增文章',   'article:create',      1, 'B'),
(212, 21, '提交审核',   'article:submit',      2, 'B'),
(213, 21, '审核通过',   'article:approve',     3, 'B'),
(214, 21, '驳回',       'article:reject',      4, 'B'),
(215, 21, '下架',       'article:unpublish',   5, 'B'),
(216, 21, '删除文章',   'article:delete',      6, 'B'),
(217, 21, '直接发布',   'article:publish',     7, 'B'),
(218, 21, '编辑文章',   'article:edit',        8, 'B');
-- 分类按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(31, 3, '新增分类', 'category:create', 1, 'B'),
(32, 3, '编辑分类', 'category:update', 2, 'B'),
(33, 3, '删除分类', 'category:delete', 3, 'B');
-- 标签按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(41, 4, '新增标签', 'tag:create', 1, 'B'),
(42, 4, '编辑标签', 'tag:update', 2, 'B'),
(43, 4, '删除标签', 'tag:delete', 3, 'B');
-- 评论按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(51, 5, '删除评论', 'comment:delete', 1, 'B');
-- 用户管理按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(611, 61, '新增用户', 'user:create', 1, 'B'),
(612, 61, '编辑用户', 'user:update', 2, 'B'),
(613, 61, '删除用户', 'user:delete', 3, 'B');
-- 角色管理按钮
INSERT INTO permission (id, parent_id, title, permission_code, sort_order, permission_type) VALUES
(621, 62, '菜单权限', 'role:manage', 1, 'B');

-- ====== 分配角色菜单权限 ======

-- admin: 所有菜单
INSERT INTO role_permission (role_id, menu_id)
SELECT (SELECT id FROM role WHERE code = 'admin'), id FROM permission;

-- reviewer: 审核 + 查看菜单
INSERT INTO role_permission (role_id, menu_id)
SELECT (SELECT id FROM role WHERE code = 'reviewer'), id FROM permission
WHERE permission_code IN (
    'dashboard:view', 'dashboard:refresh',
    'dashboard:article:stats', 'dashboard:article:chart', 'dashboard:article:recent',
    'dashboard:category:stats', 'dashboard:tag:stats', 'dashboard:comment:stats', 'dashboard:user:stats',
    'article:menu', 'article:list', 'article:edit', 'article:review', 'article:approve', 'article:reject',
    'article:unpublish', 'article:records',
    'category:list', 'tag:list', 'comment:list', 'user:list', 'role:list', 'role:menu'
);

-- user: 基础菜单
INSERT INTO role_permission (role_id, menu_id)
SELECT (SELECT id FROM role WHERE code = 'user'), id FROM permission
WHERE permission_code IN (
    'dashboard:view', 'dashboard:refresh',
    'dashboard:article:stats', 'dashboard:article:chart', 'dashboard:article:recent',
    'article:menu', 'article:list', 'article:create', 'article:edit', 'article:submit'
);

-- ====== 业务表 ======

DROP TABLE IF EXISTS article;
CREATE TABLE article (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    author_id INT8,
    category_id INT8,
    title VARCHAR(255),
    content TEXT,
    cover_image TEXT,
    status INT2 DEFAULT 0,
    reviewer_id INT8 DEFAULT 0,
    review_comment TEXT DEFAULT '',
    submitted_at TIMESTAMP,
    publish_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN article.id IS 'ID';
COMMENT ON COLUMN article.author_id IS '作者ID';
COMMENT ON COLUMN article.category_id IS '分类ID';
COMMENT ON COLUMN article.title IS '标题';
COMMENT ON COLUMN article.content IS '内容';
COMMENT ON COLUMN article.cover_image IS '首页图';
COMMENT ON COLUMN article.status IS '状态：0：草稿、1：已发布、2：已下架、3：审核中';
COMMENT ON COLUMN article.reviewer_id IS '审核人ID';
COMMENT ON COLUMN article.review_comment IS '审核意见';
COMMENT ON COLUMN article.submitted_at IS '提交审核时间';
COMMENT ON COLUMN article.publish_at IS '发布时间';
COMMENT ON COLUMN article.created_at IS '创建时间';
COMMENT ON COLUMN article.update_at IS '更新时间';
COMMENT ON TABLE article IS '文章表';

DROP TABLE IF EXISTS comment;
CREATE TABLE comment (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    parant_id INT8 NOT NULL DEFAULT 0,
    article_id INT8 NOT NULL,
    reply_user_id INT8 DEFAULT 0,
    user_id INT8 NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN comment.id IS 'ID';
COMMENT ON COLUMN comment.parant_id IS '父级评论ID';
COMMENT ON COLUMN comment.article_id IS '文章ID';
COMMENT ON COLUMN comment.reply_user_id IS '回复用户ID;可空';
COMMENT ON COLUMN comment.user_id IS '用户ID';
COMMENT ON COLUMN comment.content IS '评论内容';
COMMENT ON COLUMN comment.created_at IS '创建时间';
COMMENT ON TABLE comment IS '评论表';


DROP TABLE IF EXISTS tag;
CREATE TABLE tag (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN tag.id IS 'ID';
COMMENT ON COLUMN tag.name IS '标签名';
COMMENT ON COLUMN tag.created_at IS '创建时间';
COMMENT ON COLUMN tag.update_at IS '更新时间';
COMMENT ON TABLE tag IS '标签表';

-- 标签种子数据
INSERT INTO tag (name) VALUES ('吃瓜'), ('热议'), ('爆料'), ('辟谣'), ('社会'), ('娱乐');

DROP TABLE IF EXISTS article_tag;
CREATE TABLE article_tag (
    article_id INT8,
    tag_id INT8,
    PRIMARY KEY (article_id,tag_id)
);
COMMENT ON COLUMN article_tag.article_id IS '文章ID';
COMMENT ON COLUMN article_tag.tag_id IS '标签ID';
COMMENT ON TABLE article_tag IS '文章标签关联表';

DROP TABLE IF EXISTS category;
CREATE TABLE category (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT DEFAULT '',
    sort_order INT4 DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN category.id IS 'ID';
COMMENT ON COLUMN category.name IS '分类名';
COMMENT ON COLUMN category.description IS '分类描述';
COMMENT ON COLUMN category.sort_order IS '排序';
COMMENT ON COLUMN category.created_at IS '创建时间';
COMMENT ON COLUMN category.update_at IS '更新时间';
COMMENT ON TABLE category IS '分类表';

-- 分类种子数据
INSERT INTO category (name, description, sort_order) VALUES
    ('热点事件', '国内外重大新闻、突发事件、时事热点追踪，第一时间掌握最新动态', 1),
    ('明星八卦', '娱乐圈明星动态、绯闻爆料、综艺影视资讯，吃瓜群众的快乐源泉', 2),
    ('社会民生', '社会新闻、民生百态、法制案例、真实故事，关注百姓生活', 3),
    ('科技数码', '互联网前沿、数码产品评测、AI动态、科技创新资讯汇总', 4),
    ('奇闻趣事', '世界之大无奇不有，奇闻异事、趣味科普、冷知识一网打尽', 5);

DROP TABLE IF EXISTS article_review_record;
CREATE TABLE article_review_record (
    id INT8 GENERATED ALWAYS AS IDENTITY,
    article_id INT8 NOT NULL,
    reviewer_id INT8 NOT NULL,
    action VARCHAR(20) NOT NULL,
    comment TEXT DEFAULT '',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);
COMMENT ON COLUMN article_review_record.id IS 'ID';
COMMENT ON COLUMN article_review_record.article_id IS '文章ID';
COMMENT ON COLUMN article_review_record.reviewer_id IS '审核人ID';
COMMENT ON COLUMN article_review_record.action IS '审核操作：approve=通过, reject=驳回, unpublish=下架';
COMMENT ON COLUMN article_review_record.comment IS '审核意见';
COMMENT ON COLUMN article_review_record.created_at IS '审核时间';
COMMENT ON TABLE article_review_record IS '文章审核记录表';
CREATE INDEX IF NOT EXISTS idx_review_record_article_id ON article_review_record(article_id);
